title: 官世强
description: 我的个人博客
author: 官世强
logo: /static/img/avatar.png
github: https://guanshiqiang.com/
about: Growth Hacker

baseurl: "http://guanshiqiang.com/"
url: "http://guanshiqiang.com/"
disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
